version: '3.7'
services:
  redis:
    image: redis
  postgres:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  audress:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    restart: on-failure:3
  gnaf-importer:
    build: https://github.com/pcolusso/gnaf-importer.git
    volumes:
      - ./G-NAF:/usr/src/app/G-NAF
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    restart: on-failure:10
volumes:
  db-data:
